In [32]:
import pandas as pd
import os

In [43]:
pollutants

['RAD.csv',
 'CPC.csv',
 'TEMP.csv',
 'NOX.csv',
 'PM2.5.csv',
 'O3.csv',
 'CO.csv',
 'PREC.csv',
 'SO2.csv',
 'EC.csv',
 'PM10.csv',
 'NO2.csv',
 'NMVOC.csv']

In [116]:
########### FIRST AND LAST DAY OF ANALYSIS AND NUMBER OF MEASUREMENTS TAKEN ###########
BASE = os.path.dirname(os.path.abspath("analysis_pollutants.ipynb"))
pollutants = [f for f in os.listdir(BASE) if f.lower().endswith(".csv") and os.path.isfile(os.path.join(BASE, f))]

pollutant_unit = []
pollutant_kind = []
df_results = pd.DataFrame()
i = 0
for poll in pollutants:
    PATH_STATIONS = os.path.join(BASE,poll)
    df = pd.read_csv(PATH_STATIONS, encoding='latin-1', sep = ';', skiprows=5)
    first_day = df['Datum/Zeit'][0]
    last_day = df['Datum/Zeit'][-1:]
    length = len(df['Datum/Zeit'])
    nans = df.isna().sum().sum()
    df_new = pd.DataFrame({
        'First Day' : first_day,
        'Last Day' : last_day,
        'Length' : length,
        'Count_nan' : nans
    })
    df_results = pd.concat([df_results, df_new])
    #SAVE LIST FOR ANALYSIS
    pollutant_unit.append(pd.read_csv(PATH_STATIONS, encoding='latin-1').iloc[1,0].replace("Einheit: ",""))
    pollutant_kind.append(poll.replace(".csv",""))

df_results

       First Day    Last Day  Length  Count_nan
9313  01.01.2000  01.07.2025    9314       7900
9313  01.01.2000  01.07.2025    9314       9608
9313  01.01.2000  01.07.2025    9314       7118
9313  01.01.2000  01.07.2025    9314      10227
9313  01.01.2000  01.07.2025    9314      89257
9313  01.01.2000  01.07.2025    9314       8091
9313  01.01.2000  01.07.2025    9314       4500
9313  01.01.2000  01.07.2025    9314      18351
9313  01.01.2000  01.07.2025    9314       9392
9313  01.01.2000  01.07.2025    9314      37125
9313  01.01.2000  01.07.2025    9314      21768
9313  01.01.2000  01.07.2025    9314       9435
9313  01.01.2000  01.07.2025    9314       1678

In [120]:
df[df.isna().any(axis=1)]

      Datum/Zeit  Lugano-Università  Zürich-Kaserne  Dübendorf-Empa
32    02.02.2000                0.5             NaN             0.4
55    25.02.2000                0.4             NaN             0.0
56    26.02.2000                0.3             NaN             0.1
57    27.02.2000                0.3             NaN             0.1
64    05.03.2000                0.1             0.1             NaN
...          ...                ...             ...             ...
9309  27.06.2025                0.1             0.1             NaN
9310  28.06.2025                0.1             0.1             NaN
9311  29.06.2025                0.1             0.1             NaN
9312  30.06.2025                0.1             0.1             NaN
9313  01.07.2025                NaN             NaN             NaN

[1649 rows x 4 columns]

In [108]:
########### LIST OF UNITS USED FOR EACH POLLUTANT ###########
pollutant_unit

['W/m2',
 '1/cm3',
 'C',
 'ug/m3 eq. NO2',
 'ug/m3',
 'ug/m3',
 'mg/m3',
 'mm',
 'ug/m3',
 'ug/m3',
 'ug/m3',
 'ug/m3',
 'ppm']

In [109]:
########### LIST OF POLLUTANTS IN FOLDER ###########
pollutant_kind

['RAD',
 'CPC',
 'TEMP',
 'NOX',
 'PM2.5',
 'O3',
 'CO',
 'PREC',
 'SO2',
 'EC',
 'PM10',
 'NO2',
 'NMVOC']

In [110]:
########## ANALYSIS OF THE NUMBER OF STATIONS ##########
BASE = os.path.dirname(os.path.abspath("analysis_pollutants.ipynb"))
pollutants = [f for f in os.listdir(BASE) if f.lower().endswith(".csv") and os.path.isfile(os.path.join(BASE, f))]

i = 0
for poll in pollutants:
    PATH_STATIONS = os.path.join(BASE,poll)
    df = pd.read_csv(PATH_STATIONS, encoding='latin-1', sep = ';', skiprows=5)
    print(poll)
    if i == 0:
        ref = df.columns
    else:
        if list(df.columns) == list(ref):
            print('ok')
        else:
            print('not ok')
            print(df.columns)
            print(ref)
    i += 1

RAD.csv
CPC.csv
not ok
Index(['Datum/Zeit', 'Bern-Bollwerk', 'Lugano-Università', 'Basel-Binningen',
       'Härkingen-A1', 'Rigi-Seebodenalp'],
      dtype='object')
Index(['Datum/Zeit', 'Bern-Bollwerk', 'Lausanne-César-Roux',
       'Lugano-Università', 'Zürich-Kaserne', 'Basel-Binningen',
       'Dübendorf-Empa', 'Härkingen-A1', 'Sion-Aéroport-A9',
       'Magadino-Cadenazzo', 'Payerne', 'Tänikon', 'Beromünster', 'Chaumont',
       'Rigi-Seebodenalp', 'Davos-Seehornwald', 'Jungfraujoch'],
      dtype='object')
TEMP.csv
ok
NOX.csv
ok
PM2.5.csv
not ok
Index(['Datum/Zeit', 'Bern-Bollwerk', 'Lausanne-César-Roux',
       'Lugano-Università', 'Zürich-Kaserne', 'Basel-Binningen',
       'Dübendorf-Empa', 'Härkingen-A1', 'Sion-Aéroport-A9',
       'Magadino-Cadenazzo', 'Payerne', 'Tänikon', 'Beromünster',
       'Rigi-Seebodenalp', 'Jungfraujoch'],
      dtype='object')
Index(['Datum/Zeit', 'Bern-Bollwerk', 'Lausanne-César-Roux',
       'Lugano-Università', 'Zürich-Kaserne', 'Basel-Binningen',
       'Dübendorf-Empa', 'Härkingen-A1', 'Sion-Aéroport-A9',
       'Magadino-Cadenazzo', 'Payerne', 'Tänikon', 'Beromünster', 'Chaumont',
       'Rigi-Seebodenalp', 'Davos-Seehornwald', 'Jungfraujoch'],
      dtype='object')
O3.csv
ok
CO.csv
not ok
Index(['Datum/Zeit', 'Bern-Bollwerk', 'Lausanne-César-Roux',
       'Lugano-Università', 'Zürich-Kaserne', 'Dübendorf-Empa', 'Härkingen-A1',
       'Payerne', 'Rigi-Seebodenalp', 'Jungfraujoch'],
      dtype='object')
Index(['Datum/Zeit', 'Bern-Bollwerk', 'Lausanne-César-Roux',
       'Lugano-Università', 'Zürich-Kaserne', 'Basel-Binningen',
       'Dübendorf-Empa', 'Härkingen-A1', 'Sion-Aéroport-A9',
       'Magadino-Cadenazzo', 'Payerne', 'Tänikon', 'Beromünster', 'Chaumont',
       'Rigi-Seebodenalp', 'Davos-Seehornwald', 'Jungfraujoch'],
      dtype='object')
PREC.csv
ok
SO2.csv
not ok
Index(['Datum/Zeit', 'Lugano-Università', 'Zürich-Kaserne', 'Basel-Binningen',
       'Dübendorf-Empa', 'Härkingen-A1', 'Magadino-Cadenazzo', 'Payerne',
       'Rigi-Seebodenalp', 'Jungfraujoch'],
      dtype='object')
Index(['Datum/Zeit', 'Bern-Bollwerk', 'Lausanne-César-Roux',
       'Lugano-Università', 'Zürich-Kaserne', 'Basel-Binningen',
       'Dübendorf-Empa', 'Härkingen-A1', 'Sion-Aéroport-A9',
       'Magadino-Cadenazzo', 'Payerne', 'Tänikon', 'Beromünster', 'Chaumont',
       'Rigi-Seebodenalp', 'Davos-Seehornwald', 'Jungfraujoch'],
      dtype='object')
EC.csv
not ok
Index(['Datum/Zeit', 'Bern-Bollwerk', 'Lugano-Università', 'Zürich-Kaserne',
       'Basel-Binningen', 'Dübendorf-Empa', 'Härkingen-A1',
       'Magadino-Cadenazzo', 'Payerne', 'Rigi-Seebodenalp'],
      dtype='object')
Index(['Datum/Zeit', 'Bern-Bollwerk', 'Lausanne-César-Roux',
       'Lugano-Università', 'Zürich-Kaserne', 'Basel-Binningen',
       'Dübendorf-Empa', 'Härkingen-A1', 'Sion-Aéroport-A9',
       'Magadino-Cadenazzo', 'Payerne', 'Tänikon', 'Beromünster', 'Chaumont',
       'Rigi-Seebodenalp', 'Davos-Seehornwald', 'Jungfraujoch'],
      dtype='object')
PM10.csv
ok
NO2.csv
ok
NMVOC.csv
not ok
Index(['Datum/Zeit', 'Lugano-Università', 'Zürich-Kaserne', 'Dübendorf-Empa'], dtype='object')
Index(['Datum/Zeit', 'Bern-Bollwerk', 'Lausanne-César-Roux',
       'Lugano-Università', 'Zürich-Kaserne', 'Basel-Binningen',
       'Dübendorf-Empa', 'Härkingen-A1', 'Sion-Aéroport-A9',
       'Magadino-Cadenazzo', 'Payerne', 'Tänikon', 'Beromünster', 'Chaumont',
       'Rigi-Seebodenalp', 'Davos-Seehornwald', 'Jungfraujoch'],
      dtype='object')